# Generated by Django 3.0.3 on 2020-11-18 17:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 17, 0, 37, 552558, tzinfo=utc)),
        ),
    ]
