# Generated by Django 3.0.3 on 2020-11-18 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201118_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 17, 1, 2, 597891, tzinfo=utc)),
        ),
    ]
