# Generated by Django 3.0.3 on 2020-12-06 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_api', '0003_auto_20201206_0914'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='todo',
            unique_together={('task', 'date')},
        ),
    ]
